### PR TITLE
Slightly refactored StickerPreview

### PR DESCRIPTION
**Pull request by monich**
I just love stickers :)

1. Removed mouse area stealing mouse events and not allowing context menu to appear when sticker is long-tapped
2. Don't load placeholder image right away, most of the time (pretty much always) they get very quickly replaced with the actual images which doesn't look great
3. Parent already provides enough paddings, there's no need to more
4. Simplified layout rules
5. Use `FadeAnimation` for animating opacity
6. `QtGraphicalEffects` import is not needed
7. Renamed `singleImage` into `stickerImage`

### CODE REVIEW

**Review by Wunderfitz — CHANGES_REQUESTED** [review]
I also love stickers :) - however, something seems to be wrong with the sizing, see the screenshot of my device...

image

**Comment by monich** [comment]
Yes, indeed - if I enable "Show stickers as images" I get that too. My bad, will take another look.

**Comment by monich** [comment]
I think I fixed that. Please try again!

**Review by Wunderfitz — APPROVED** [review]
Looks good now, thanks for the change! :)

**Pull request merged**
