### PR TITLE
Fix new line in TextInput when using Send By Enter

### LINKED ISSUE #406: Text input inputs newline when you hit enter
When you have selected in options "send message with enter" and you press enter with the cursor between lines in a message, then the message is sent but with a line break where cursor position
photo5911117761424242177
photo5911117761424242178

### PR DESCRIPTION
**Pull request by santhoshmanikandan**
Fixed the issue by removing the enter that gets added to textarea
when enter is pressed using string operations.

Fixes #406

### CODE REVIEW

**Comment by Wunderfitz** [comment]
Thanks for that, seems to be fine. 

Strange though that there seem to be Git conflicts. Could you please check and resolve them?

**Comment by simonschmeisser** [comment]
This branch is based on a very old state of the repo, you will need to rebase

**Comment by Wunderfitz** [comment]
Would you mind rebasing your branch and update the PR afterwards? Otherwise I might simply copy the two lines to the main branch manually...

**Comment by santhoshmanikandan** [comment]
Sorry, have rebased my branch now. Kindly check now. If it's still breaking, kindly go ahead of copy the changes to the main branch manually.

**Comment by simonschmeisser** [comment]
Actually you merged the master branch into your PR instead of rebasing your branch to the master branch. The code looks the same but the resulting git history looks quite different. Here is what I usually do
```
git remote add upstream https://github.com/Wunderfitz/harbour-fernschreiber.git
git fetch --all
git checkout bug-fix#406
git rebase upstream/master
# compile and test
git push --force-with-lease
```
see https://docs.gitlab.com/ee/topics/git/git_rebase.html or many other tutorials for more information

**Comment by santhoshmanikandan** [comment]
> Actually you merged the master branch into your PR instead of rebasing your branch to the master branch. The code looks the same but the resulting git history looks quite different. Here is what I usually do
> 
> ```
> git remote add upstream https://github.com/Wunderfitz/harbour-fernschreiber.git
> git fetch --all
> git checkout bug-fix#406
> git rebase upstream/master
> # compile and test
> git push --force-with-lease
> ```
> 
> see https://docs.gitlab.com/ee/topics/git/git_rebase.html or many other tutorials for more information

Sure thanks for you steps. I will close this PR as it messes the history.

**Comment by simonschmeisser** [comment]
no need to close it, you can just push to your branch and it will be updated automatically

**Comment by santhoshmanikandan** [comment]
On doing the changes, this pull request got closed automatically without an option to reopen. So created a new pull request [here](https://github.com/Wunderfitz/harbour-fernschreiber/pull/416)

**Pull request closed without merging**
