### PR TITLE
Updated harbour-fernschreiber-sk.ts

### PR DESCRIPTION
**Pull request by okruhliak**
Video notes text on chat list translated.

### CODE REVIEW

**Review by Wunderfitz — CHANGES_REQUESTED** [review]
Seems that the changes are not up-to-date... Seems that you try to resubmit the original translation again. Could you please check?

**Comment by okruhliak** [comment]
Hello,
what do I have to do to make it commit, because it's okay in my fork?
L.

Dňa Utorok, 26. januára 2021,  Sebastian Wolf napísal:
> @Wunderfitz requested changes on this pull request.
> 
> Seems that the changes are not up-to-date... Seems that you try to resubmit the original translation again. Could you please check?
> 
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Wunderfitz/harbour-fernschreiber/pull/339#pullrequestreview-57681600

-- 
Odoslané z môjho Sailfish OS telefónu

**Comment by Wunderfitz** [comment]
Seems that the conflict still exist, see the warning message in this thread...

You need to sync your fork with the upstream repository, please see the documentation for details: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Comment by Wunderfitz** [comment]
I cherry-picked your changes and pushed them to the master branch. I'll close this pull request now. My recommendation now: Perform a hard reset of your fork to be on par with upstream (this repository). A manual how to do that is available here: https://stackoverflow.com/questions/9646167/clean-up-a-fork-and-restart-it-from-the-upstream

**Pull request closed without merging**
