### PR TITLE
Bugfix/fix some warnings

### PR DESCRIPTION
**Pull request by jgibbon**

### CODE REVIEW

**Comment by monich** [comment]
While you're on it... In addition to this `draft_message` warning I'm also getting this after visiting a channel where I can't post:
```
[D] TDLibReceiver::receiverLoop:159 - [TDLibReceiver] Raw result: {
    "@type": "error",
    "code": 400,
    "message": "Need administrator rights in the channel chat"
}
```
Which results in an error message flying across the screen.

**Comment by jgibbon** [comment]
> While you're on it... In addition to this `draft_message` warning I'm also getting this after visiting a channel where I can't post:
> 
> ```
> [D] TDLibReceiver::receiverLoop:159 - [TDLibReceiver] Raw result: {
>     "@type": "error",
>     "code": 400,
>     "message": "Need administrator rights in the channel chat"
> }
> ```
> 
> Which results in an error message flying across the screen.

I think this may have been fixed yesterday with 1e4455482c295aa2bce7cf16b7979a7a27dc96b8 (thanks, @Wunderfitz )

**Comment by monich** [comment]
> I think this may have been fixed yesterday with [1e44554](https://github.com/Wunderfitz/harbour-fernschreiber/commit/1e4455482c295aa2bce7cf16b7979a7a27dc96b8) (thanks, @Wunderfitz )

Ok, cool! My build was slightly older than that.

**Comment by Wunderfitz** [comment]
Thx!

**Pull request merged**
