### PR TITLE
Always append last message content to notifications

### PR DESCRIPTION
**Pull request by dscheinah**
I usually read and dismiss notifications on my smartwatch and only use the phone if I need to reply. This currently does not work for subsequent messages as the content is hidden.

With this PR the message content will always be appended to the notification. This allows me read all messages on the watch without using the phone if not needed.

I also removed the duplicated `nemoNotification->setBody(notificationBody);` line.

### CODE REVIEW

**Review by Wunderfitz — CHANGES_REQUESTED** [review]
I'm open to that, but only if
- it's made configurable
- it's not the default
Could you maybe include that in the settings? We already have a nice set of notification settings under 'Behavior'.
(And sorry for the late response...)

**Comment by dscheinah** [comment]
No problem. I will see if I can do it in an acceptable way. But it may take a while because I'm quite busy at the moment.

How should I handle translations and do I need to take care of something special regarding persistence and migration?

**Comment by dscheinah** [comment]
Alright, it's now added as a setting with off as default. Translations are mostly unfinished.

**Comment by dscheinah** [comment]
Ok, fixed, so it should be ready now

**Comment by jgibbon** [comment]
Thanks for your work – that seems like a worthwhile addition. Hadn't had the time to review yet, just wanted to show some appreciation.

**Comment by Wunderfitz** [comment]
Far too late, but thanks! Let's merge and test. :)

**Comment by dscheinah** [comment]
Great - thanks :) For testing I just realized that I obviously used my own build for a while now - because I already have the feature enabled.

**Pull request merged**
