### PR TITLE
Updated spanish transtation

### PR DESCRIPTION
**Pull request by GNUuser**
Can you explain me which  feature is Ln: 1705

### CODE REVIEW

**Comment by Wunderfitz** [comment]
Sure. By default, the app waits a second until a message that is on the screen is marked as read. If you switch this feature off, a message will immediately marked as read once it's on the screen (and you're not scrolling at the moment).

**Comment by Wunderfitz** [comment]
Gracias

**Comment by GNUuser** [comment]
Ok i checking......

**Comment by GNUuser** [comment]
Very confusing this feature, and may be not useful. But i will how fix this confusing..

**Pull request merged**
