### PR TITLE
Update functions.js

### PR DESCRIPTION
**Pull request by GNUuser**
#203

### CODE REVIEW

**Comment by Wunderfitz** [comment]
What's the motivation behind this change?

Regards, Sebastian

**Comment by GNUuser** [comment]
Those string I deleted is not useful, and mess up the Fernschreiber interface.

**Comment by GNUuser** [comment]
I was tracking this issue from Fernschreiber v0.3 and already quick fixed in #218

**Comment by Wunderfitz** [comment]
I'd disagree here - even the official client says something like "last seen recently". With this case, Fernschreiber would only say for example "two minutes ago" without anything else. I don't see why the current text would be too messy...

**Comment by GNUuser** [comment]
Trust me  something is wrong there before my changes. Ln: 169, 171, 173 are not correct.

**Comment by GNUuser** [comment]
In line: 173 may be is correct "last seen recently" but not "offline, last online:"

**Comment by Wunderfitz** [comment]
There is a dedicated status for "last seen recently" and it's handled in https://github.com/Wunderfitz/harbour-fernschreiber/blob/master/qml/js/functions.js#L176 - See also the statuses from https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_user_status.html

**Comment by GNUuser** [comment]
offline, was recently online

> There is a dedicated status for "last seen recently" and it's handled in https://github.com/Wunderfitz/harbour-fernschreiber/blob/master/qml/js/functions.js#L176 - See also the statuses from https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_user_status.html

You talk about line 177 I do not touched the line, but also need fix by removing "offline, was" .

**Comment by GNUuser** [comment]
Check my es.ts history I see how I focus too much in those line, to get correct and optimized sentences.

**Comment by Wunderfitz** [comment]
Well yes, I was wondering a bit why you changed certain strings back and forth, but that's OK. :) My Spanish is not that good that I can assess that and as long as there are no other people asking for a different translation, that's OK with me. If you want to change the original strings, however, you probably need to convince others as well. I'm really open to a shorter version, but that should be consistent and also still convey the respective status message.

Maybe let's better discuss that in the Telegram group...

**Comment by GNUuser** [comment]
Sounds good, thank you. :  )

**Comment by GNUuser** [comment]
Just remember that Fernschreiber it is not a book, It is a FANCY app like Telegram client to Sailfish OS running on an electronic device. Be careful not to put too many messages in plain text. ; )

**Comment by jgibbon** [comment]
I think these changes lead to losing context a bit.
But I understand your problem and would propose a compromise. 
For example just removing "offline, " everywhere, since that is sufficiently implied with the rest of the strings.

**Comment by Wunderfitz** [comment]
Yep, removing 'offline, ' only would be something I would also approve!

**Comment by GNUuser** [comment]
Well some lines I deleted  only "offline".  We need to use only essential phrases, the English language its phrases are small, but other languages the phrases are long or medium, this is a problem when translating a string of words in portrait mode. In Spanish language it is extremely explicit and most of the sentences are long, so to translate Fernschreiber I am using advanced Spanish, to reach the correct size of the word string. Right now my translation is nice in newer version 0.5.1.
Issues examples
Truly -> Verdaderamente

**Comment by monich** [comment]
+1 for replacing "offline, last online:"  with just "last online:"

**Comment by Wunderfitz** [comment]
As the majority here was voting to only remove the 'offline' text, but nothing more, I did that with commit 633f765c8028ec40a7aabca741572fa3f88628ec. Moreover, I also changed the translations accordingly so that there are no additional 'unfinished' entries there.

@GNUuser I'll close this PR because of that change. As said, the Spanish translation is up to you (I haven't changed your shorter translation) unless there are other people asking to get closer to the original wording. 

Thanks colleages and best regards, Sebastian

**Comment by GNUuser** [comment]
Mmm I find where is the problem, one string coming from directly from Telegram api, already do "offline, last online:"

**Comment by GNUuser** [comment]
> As the majority here was voting to only remove the 'offline' text, but nothing more, I did that with commit [633f765](https://github.com/Wunderfitz/harbour-fernschreiber/commit/633f765c8028ec40a7aabca741572fa3f88628ec). Moreover, I also changed the translations accordingly so that there are no additional 'unfinished' entries there.
> 
> @GNUuser I'll close this PR because of that change. As said, the Spanish translation is up to you (I haven't changed your shorter translation) unless there are other people asking to get closer to the original wording.
> 
> Thanks colleages and best regards, Sebastian

Yes close it. Thank you.

**Comment by GNUuser** [comment]
I am 110% confident that the issue or confusing is coming from the sentence(Ago) coming directly from Telegram api, so "offline, last online:" - > "Ago". I found the bug today, but I am okay with your changes, I just reporting to Fernschreiber  team.
Also I already readed the translations TelegramApi recommendations. @Wunderfitz @jgibbon @monich

**Pull request closed without merging**
