### PR TITLE
Highlight unread Converstations

### PR DESCRIPTION
**Pull request by nephros**
A proposed solution for Issue #512

### CODE REVIEW

**Comment by monich** [comment]
IMO badge is a good enough mark. More fonts and colors don't necessarily make UI better.

On the other hand, since there's at least one person in the world who likes it this way, then if this behavior is configurable (and off by default) - why not.

**Review by Wunderfitz — CHANGES_REQUESTED** [review]
I agree with @monich - I'm actually pretty happy with the way how it looks like at the moment. But if you make it configurable and not the default, I'm happy to merge it. (and sorry for the late response)

**Comment by carlosgonz0** [comment]
Hi any ETA to merge this then new realease.? 
Thanks of advance all.

**Comment by carlosgonz0** [comment]
@nephros where are you to push this.

**Comment by Wunderfitz** [comment]
A little late, but as we do a new version, let's merge it. Thank you very much!

**Pull request merged**
