### PR TITLE
Take logging categories into use

### PR DESCRIPTION
**Pull request by monich**
Logging can be enabled in release build like this:
```bash
QT_LOGGING_RULES="fernschreiber.*=true" harbour-fernschreiber
```
See https://doc.qt.io/qt-5/qloggingcategory.html for more details.

### CODE REVIEW

**Comment by jgibbon** [comment]
Oh, a slight misunderstanding: I thought you'd just take over the other PR/branch and add to that. 
But no worries, the only thing that collides is the `debuglog.h` but that may be easily merged..

I guess it would now make sense to get this one merged first and then rebase #185 to this to continue there?

cheers

**Comment by monich** [comment]
Oh, I haven't actually noticed `debuglog.h`, my bad :/

**Comment by monich** [comment]
Maybe rename it into something like `debuglogjs.h` or something? This one doesn't need to be included from every C++ file.

**Comment by jgibbon** [comment]
Yeah, or *frontend.h or something. Makes sense.

**Pull request merged**
