### PR TITLE
First translation to Slovak

### PR DESCRIPTION
**Pull request by okruhliak**
I hope it is OK.

### CODE REVIEW

**Comment by jgibbon** [comment]
Thank you!
On first glance, it looks brilliant! There are a few strings where you don't have the same interpunctuation, but I'd say that's your decision and totally fine.

We'll have another look soon and add it to the "used files" for compilation after merging.
In the mean time feel free to add yourself to the README.md if you have any preferences regarding the name you prefer.

cheers!

**Comment by jgibbon** [comment]
Oh, and feel free to join the Fernschreiber development group on Telegram if you're interested. 
We usually announce new releases there to give translators a chance to keep up and discuss implementation details (and if you're willing to test new features before they're released, sometimes we post debug builds in between).

You'll find the link here: https://github.com/Wunderfitz/harbour-fernschreiber/issues/162

cheers!

**Comment by okruhliak** [comment]
Hi,

thanks for your feedback.
Can you send me differences interpunctuation, please?

I added Slovak into README.md.

I do not know if I have any restrictions set in the browser, but I can't join the group, the button doesn't respond.

Regards
Ladislav

Dňa Pondelok, 25. januára 2021,  jgibbon napísal:
> Thank you!
> On first glance, it looks brilliant! There are a few strings where you don't have the same interpunctuation, but I'd say that's your decision and totally fine.
> 
> We'll have another look soon and add it to the "used files" for compilation after merging.
> In the mean time feel free to add yourself to the README.md if you have any preferences regarding the name you prefer.
> 
> cheers!
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Wunderfitz/harbour-fernschreiber/pull/337#issuecomment-76662016

-- 
Odoslané z môjho Sailfish OS telefónu

**Comment by jgibbon** [comment]
You should be able to join with Fernschreiber, as well.

Those differences really are nothing of consequence, you can really leave it if it's more common in your language like that. 
No worries. I don't even think we thought about that much while doing the source texts. But here you are:

 - "This group is empty." 
 - "Connecting to proxy..."
 - "You don't have any contacts."

Thanks, again!

**Comment by okruhliak** [comment]
I fixed it, it was my fault, I'm sorry.

**Comment by jgibbon** [comment]
Small heads up: 
While adding, I noticed that there are a few new strings since you began translating. See 1701562c4238f907b952194f407b5b4b6539f4ee for details.

**Comment by okruhliak** [comment]
Sorry, supplemented.



Dňa Pondelok, 25. januára 2021,  jgibbon napísal:
> Small heads up: 
> While adding, I noticed that there are a few new strings since you began translating. See 1701562c4238f907b952194f407b5b4b6539f4ee for details.
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/Wunderfitz/harbour-fernschreiber/pull/337#issuecomment-76667736

-- 
Odoslané z môjho Sailfish OS telefónu

**Pull request merged**
