### PR TITLE
Removed mutex from ChatModel

### PR DESCRIPTION
**Pull request by monich**
It appears to be useless, at least I couldn't figure out what's being synchronized with what

### CODE REVIEW

**Comment by Wunderfitz** [comment]
Well, I simply wanted to be cautious at the beginning in order to avoid race conditions and similar things. But of it works without, I'm fine with it. Will test it shortly and merge if I don't encounter any obvious issues...

**Comment by Wunderfitz** [comment]
No suspicious things notices, let's merge. Can re-introduce the mutex in case we need it...

**Comment by monich** [comment]
Introducing new entities without necessity is almost never a good idea ))

**Comment by Wunderfitz** [comment]
That's so true. However, I was a little desperate at that time as I had quite a few strange issues in both the chat list and the chat model...

**Pull request merged**
