### PR TITLE
Added storage optimizer option

### PR DESCRIPTION
**Pull request by monich**
I'm not quite sure what it does but it sounds important :)

### CODE REVIEW

**Comment by Wunderfitz** [comment]
No problem with merging unfinished stuff, but as long as the option doesn't do anything, maybe we should hide it from the default settings view, shouldn't we?

**Comment by monich** [comment]
It's supposed to periodically [remove](https://github.com/tdlib/td/issues/667) old data.

**Comment by Wunderfitz** [comment]
That's it? Well, OK - then let's merge it! :D

**Comment by monich** [comment]
If it actually works (which it probably does) then later its parameters (size limit, time limit etc.) can be made configurable too.

**Pull request merged**
